---
- name: Ensure hostname is configured
  hostname:
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  register: hostname
  tags: hostname

- name: Create user named kube
  user:
    name: kube
    groups: kube,sudo
    append: yes
    password: "{{ kube_password }}"

- name: Deploy SSH Key
  authorized_key: user=kube
    key="{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    state=present

- name: Disable password authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
    backup=yes
  with_items:
    - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^UsePAM', line: 'UsePAM no' }
    - { regexp: '^ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication no' }
  notify:
    - restart ssh

- name: "Remove old user accounts"
  become_user: kube
  user:
    name: pi
    state: absent

- name: Set timezone to UTC
  timezone:
    name: UTC
  register: timezone

- name: Set locale to en_US.UTF-8
  locale_gen:
    name: en_US.UTF-8
    state: present
